volumes:
  pg_dev_data:
  redis_dev_data:
  backend_venv:

services:
  postgres:
    image: postgis/postgis:18-3.6
    container_name: postgres
    env_file: ./backend/.env
    volumes:
      - pg_dev_data:/var/lib/postgresql
    # restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    volumes:
      - redis_dev_data:/data
    # restart: unless-stopped

  frontend1:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: /frontend1
    environment:
      - NODE_ENV=production
      # - NEXT_PUBLIC_BACKEND_ORIGIN=http://nginx:80
    # restart: unless-stopped

  frontend2:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: /frontend2
    environment:
      - NODE_ENV=production
      # - NEXT_PUBLIC_BACKEND_ORIGIN=http://nginx:80
    # restart: unless-stopped

  backend:
    build: ./backend
    container_name: backend
    env_file: ./backend/.env
    depends_on:
      - postgres
      - redis
    volumes:
      - backend_venv:/app/.venv
    # restart: unless-stopped

  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - frontend1
      - frontend2
      - backend
    # restart: unless-stopped
